### ISSUE TITLE
unable to use this plugin with elasticsearch shield security

### ISSUE THREAD

**Issue by dogfish182** [s12v/newrelic-elasticsearch#10]
does not support giving basic authentication as username:pass@localhost in config file. 

a work around for this is to configure anonymous authentication for shield, however I don't know what permissions to create in the roles as I'm not sure which operations are being performed on startup, which indices and cluster operations must I allow? 

error on running with a shield secured node in foreground (esearch 1.5)

Exception in thread "main" java.lang.IllegalArgumentException: URI can't be null.
        at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:147)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1098)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
        at me.snov.newrelic.elasticsearch.parsers.AbstractParser.getInputStream(Unknown Source)
        at me.snov.newrelic.elasticsearch.parsers.AbstractParser.request(Unknown Source)
        at me.snov.newrelic.elasticsearch.ElasticsearchAgent.getClusterName(Unknown Source)
        at me.snov.newrelic.elasticsearch.ElasticsearchAgent.<init>(Unknown Source)
        at me.snov.newrelic.elasticsearch.ElasticsearchAgentFactory.createConfiguredAgent(Unknown Source)
        at com.newrelic.metrics.publish.AgentFactory.createAndRegister(AgentFactory.java:97)
        at com.newrelic.metrics.publish.AgentFactory.createConfiguredAgents(AgentFactory.java:57)
        at com.newrelic.metrics.publish.Runner.createAgents(Runner.java:135)
        at com.newrelic.metrics.publish.Runner.setupAgents(Runner.java:142)
        at com.newrelic.metrics.publish.Runner.setupAndRun(Runner.java:103)
        at me.snov.newrelic.elasticsearch.Main.main(Unknown Source)
[13:27:29] [ERROR] npi - [Error: Error while starting plugin process in foreground]

**Comment by preflightsiren** [comment]
:+1: that would be very useful for me too.
