### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by equake** [s12v/newrelic-elasticsearch#2]
Hello!

I'm trying to install this plugin but I've got this error. What can I do? 

Thanks!

SEVERE: An error has occurred
java.lang.NullPointerException
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.reportNodeStats(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.reportNodesStats(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.pollCycle(Unknown Source)
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by davidgibbons** [comment]
I have this same error.

[root@ newrelic-npi]# ./npi start me.snov.newrelic-elasticsearch --foreground
[16:12:09] [INFO] operations - Starting plugin 'me.snov.newrelic-elasticsearch' in foreground...
[16:12:09] [INFO] operations - Please visit https://rpm.newrelic.com to verify that the plugin is successfully reporting to your account. It may take a few minutes to become visible.
INFO: Using configuration file /root/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-1.3.0/config/newrelic.json
INFO: Using configuration file /root/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-1.3.0/config/plugin.json
INFO: New Relic monitor started
SEVERE: An error has occurred
java.lang.NullPointerException
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.reportNodeStats(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.reportNodesStats(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.pollCycle(Unknown Source)
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

**Comment by s12v** [comment]
@equake, @davidgibbons, which elasticsearch version do you use?

**Comment by davidgibbons** [comment]
1.4.2

**Comment by equake** [comment]
1.4.2 also! 
here is my /_cluster/status json. hope that helps :)

{"timestamp":1425656807562,"cluster_name":"jacotei_search","status":"green","indices":{"count":6,"shards":{"total":60,"primaries":30,"replication":1.0,"index":{"shards":{"min":10,"max":10,"avg":10.0},"primaries":{"min":5,"max":5,"avg":5.0},"replication":{"min":1.0,"max":1.0,"avg":1.0}}},"docs":{"count":7662949,"deleted":3265648},"store":{"size_in_bytes":21102222468,"throttle_time_in_millis":2719280},"fielddata":{"memory_size_in_bytes":241827072,"evictions":0},"filter_cache":{"memory_size_in_bytes":391154132,"evictions":4772197},"id_cache":{"memory_size_in_bytes":0},"completion":{"size_in_bytes":0},"segments":{"count":627,"memory_in_bytes":152383046,"index_writer_memory_in_bytes":0,"index_writer_max_memory_in_bytes":448123690,"version_map_memory_in_bytes":1953968,"fixed_bit_set_memory_in_bytes":0},"percolate":{"total":0,"time_in_millis":0,"current":0,"memory_size_in_bytes":-1,"memory_size":"-1b","queries":0}},"nodes":{"count":{"total":28,"master_only":0,"data_only":0,"master_data":2,"client":26},"versions":["1.2.2","1.4.2"],"os":{"available_processors":10,"mem":{"total_in_bytes":8241627136},"cpu":[{"vendor":"Intel","model":"Xeon","mhz":2393,"total_cores":4,"total_sockets":4,"cores_per_socket":16,"cache_size_in_bytes":8192,"count":1}]},"process":{"cpu":{"percent":4},"open_file_descriptors":{"min":127,"max":2626,"avg":1989}},"jvm":{"max_uptime_in_millis":1553453190,"versions":[{"version":"1.8.0_31","vm_name":"OpenJDK 64-Bit Server VM","vm_version":"25.31-b07","vm_vendor":"Oracle Corporation","count":4},{"version":"1.7.0_71","vm_name":"OpenJDK 64-Bit Server VM","vm_version":"24.65-b04","vm_vendor":"Oracle Corporation","count":24}],"mem":{"heap_used_in_bytes":5345863280,"heap_max_in_bytes":50931433472},"threads":14041},"fs":{"total_in_bytes":82586656768,"free_in_bytes":70012657664,"available_in_bytes":65810595840,"disk_reads":4569017,"disk_writes":20769116,"disk_io_op":25338133,"disk_read_size_in_bytes":114036380672,"disk_write_size_in_bytes":2935468302336,"disk_io_size_in_bytes":3049504683008,"disk_queue":"0","disk_service_time":"3.4"},"plugins":[{"name":"bigdesk","version":"NA","description":"No description found.","url":"/_plugin/bigdesk/","jvm":false,"site":true},{"name":"HQ","version":"NA","description":"No description found.","url":"/_plugin/HQ/","jvm":false,"site":true},{"name":"head","version":"NA","description":"No description found.","url":"/_plugin/head/","jvm":false,"site":true},{"name":"analysis-icu","version":"2.4.1","description":"UTF related ICU analysis support","jvm":true,"site":false}]}}

**Comment by s12v** [comment]
@equake, thank you. Could you please also provide `/_nodes/stats` output?

**Comment by s12v** [comment]
@davidgibbons, I've tested it with 1.4.2, and can't reproduce. Could you please send your /_nodes/stats output as well? Probably the output of your nodes stats is different and plugin fails.

**Comment by davidgibbons** [comment]
Emailed directly because I don't want to fuss with removing hostname info
but also don't want to publish that in github

**Comment by s12v** [comment]
@davidgibbons, thank you, I could reproduce it, working on a fix

**Comment by s12v** [comment]
@equake, @davidgibbons, please install plugin version 1.3.1

The problem is, some nodes does not report OS stats, like load average, CPU & mem usage. Compare https://github.com/s12v/newrelic-elasticsearch/blob/master/test/resources/nodes_stats_1.4.2.json#L119-L146 and https://github.com/s12v/newrelic-elasticsearch/blob/master/test/resources/nodes_stats_1.4.2_incomplete_os_stats.json#L119-L121

**Comment by s12v** [comment]
Fixed: https://github.com/s12v/newrelic-elasticsearch/commit/0e1e95e9260dd1ecff0b413c355425e03cf2d183
