### ISSUE TITLE
npi error after 2.1.0 upgrade

### ISSUE THREAD

**Issue by jdavisclark** [s12v/newrelic-elasticsearch#27]
npi CLI operations bomb out for the most part after fetching this plugin after the `2.1.0` upgrade. I think its because the directory structure changed. previously the plugin path looked like `plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-2.0.0`, now it is `plugins/me.snov.newrelic-elasticsearch` (no versioned directory); not sure though.

error from `npi list` (and some others) after installing `v2.1.0`:

```
[16:10:29] [ERROR] npi - Arguments to path.join must be strings
[16:10:29] [ERROR] npi - TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at isPreparedSync (/Users/davis/newrelic-npi/lib/platform_helpers.js:197:29)
    at Object.getLocalPluginState (/Users/davis/newrelic-npi/lib/platform_helpers.js:410:8)
    at onEachIteration (/Users/davis/newrelic-npi/lib/operations.js:306:17)
    at Array.forEach (native)
    at onGetLocalPluginsComplete (/Users/davis/newrelic-npi/lib/operations.js:305:15)
    at onReaddirComplete (/Users/davis/newrelic-npi/lib/platform_helpers.js:378:12)
    at ReaddirReq.Req.done (/Users/davis/newrelic-npi/node_modules/unzip/node_modules/fstream/node_modules/graceful-fs/graceful-fs.js:143:5)

```

**Comment by btsuhako** [comment]
I'm having the same error on a clean installation of NPI v0.1.5 and Elasticsearch 2.2.0

**Comment by jdavisclark** [comment]
@s12v: fyi, fixing the directory structure will take care of it.

**Comment by archongtv** [comment]
Same error here. NPI 0.1.5 + ES 2.2.0.

**Comment by ahmetfay** [comment]
same error here. NPI v0.1.5 + ES 1.7.1

**Comment by vrga** [comment]
i've been getting this on trying to install this for the first time:
`
[13:57:55] [ERROR] npi - [Error: Invalid compression format, NPI currently supports tar.gz and zip compression]
`

**Comment by ghettodev** [comment]
I believe it's downloading the 404 page.

```
curl -I https://github.com/s12v/newrelic-elasticsearch/releases/download/2.1.0/newrelic-elasticsearch-plugin-2.1.0.tar.gz
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Wed, 24 Feb 2016 18:43:52 GMT
Content-Type: application/json; charset=utf-8
Status: 404 Not Found
```

**Comment by btsuhako** [comment]
If you want to install the previous version, in your NPI installation directory create a `config/manifest.json` file with the following contents:

``` [
  {
    "guid": "me.snov.newrelic-elasticsearch",
    "download_url": "https://github.com/s12v/newrelic-elasticsearch/releases/download/2.0.0/newrelic-elasticsearch-plugin-2.0.0.tar.gz",
    "version": "2.0.0",
    "installer_compatible": true,
    "implementation": "Java"
  }
]
```

It may gripe about downloading the file, but I was successfully able to rollback yesterday doing this.

**Comment by s12v** [comment]
Should be fixed with 2.1.1. Sorry for the inconvenience.

**Comment by archongtv** [comment]
Will it work with 2.2.0?

**Comment by ahmetfay** [comment]
Thnx Sergey, it's working now :)

**Comment by s12v** [comment]
@archongtv, personally I haven't tried it with ES 2.2.0, but at least existing tests are not failing: https://travis-ci.org/s12v/newrelic-elasticsearch/jobs/111588883 :)
