### ISSUE TITLE
IllegalArgumentException: URI can't be null

### ISSUE THREAD

**Issue by dmarlow** [s12v/newrelic-elasticsearch#3]
Exception in thread "main" java.lang.IllegalArgumentException: URI can't be null.
    at sun.net.spi.DefaultProxySelector.select(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at me.snov.newrelic.elasticsearch.parsers.AbstractParser.getInputStream(Unknown Source)
    at me.snov.newrelic.elasticsearch.parsers.AbstractParser.request(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.getClusterName(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.<init>(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgentFactory.createConfiguredAgent(Unknown Source)
    at com.newrelic.metrics.publish.AgentFactory.createAndRegister(AgentFactory.java:97)
    at com.newrelic.metrics.publish.AgentFactory.createConfiguredAgents(AgentFactory.java:57)
    at com.newrelic.metrics.publish.Runner.createAgents(Runner.java:135)
    at com.newrelic.metrics.publish.Runner.setupAgents(Runner.java:142)
    at com.newrelic.metrics.publish.Runner.setupAndRun(Runner.java:103)
    at me.snov.newrelic.elasticsearch.Main.main(Unknown Source)

I'm using the HTTP basic auth plugin and am trying to use a "host" value in the following format: username:password@some.host:port

**Comment by dogfish182** [comment]
I'm also having the exact same issue.

**Comment by s12v** [comment]
Solved by https://github.com/s12v/newrelic-elasticsearch/pull/24
