### ISSUE TITLE
Error running Docker version on Amazon EC2

### ISSUE THREAD

**Issue by allansene** [s12v/newrelic-elasticsearch#65]
I'm getting this error, using the docker image in an Amazon EC2 machine:

```
[21:17:42] [INFO] operations - Generating 'newrelic.json' file for plugin...
[21:17:42] [INFO] operations - Running in 'noedit' mode, not opening plugin configuration file.
sed: -e expression #1, char 16: unknown option to `s'
```

Anybody know what could be occasioning that?

**Comment by allansene** [comment]
When running the *npi* version, got this:

```
INFO: Using configuration file /home/ec2-user/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-2.3.0/config/newrelic.json
INFO: Using configuration file /home/ec2-user/newrelic-npi/plugins/me.snov.newrelic-elasticsearch/newrelic-elasticsearch-plugin-2.3.0/config/plugin.json
Exception in thread "main" java.lang.IllegalArgumentException: URI can't be null.
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:147)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1132)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at me.snov.newrelic.elasticsearch.parsers.AbstractParser.getInputStream(AbstractParser.java:45)
	at me.snov.newrelic.elasticsearch.parsers.AbstractParser.request(AbstractParser.java:51)
	at me.snov.newrelic.elasticsearch.ElasticsearchAgentFactory.createConfiguredAgent(ElasticsearchAgentFactory.java:45)
	at com.newrelic.metrics.publish.AgentFactory.createAndRegister(AgentFactory.java:97)
	at com.newrelic.metrics.publish.AgentFactory.createConfiguredAgents(AgentFactory.java:57)
	at com.newrelic.metrics.publish.Runner.createAgents(Runner.java:135)
	at com.newrelic.metrics.publish.Runner.setupAgents(Runner.java:142)
	at com.newrelic.metrics.publish.Runner.setupAndRun(Runner.java:103)
	at me.snov.newrelic.elasticsearch.Main.main(Main.java:12)
```

**Comment by allansene** [comment]
Just found the mistake... I was passing `http//` on the host :|

**Comment by s12v** [comment]
@allansene, funny, I had exactly the same issue a couple of days ago :)) Right, just use `ES_PROTOCOL`
