### ISSUE TITLE
Exception in daemon.log

### ISSUE THREAD

**Issue by viktor-evdokimov** [s12v/newrelic-elasticsearch#8]
at me.snov.newrelic.elasticsearch.reporters.NodesStatsReporter.reportNodesStats(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.pollCycle(Unknown Source)
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Plugin report running but not sending data to newrelic

After stopping and starting with sudo I've got 

java.lang.NullPointerException
    at me.snov.newrelic.elasticsearch.reporters.NodesStatsReporter.reportSearch(Unknown Source)
    at me.snov.newrelic.elasticsearch.reporters.NodesStatsReporter.reportNodeStats(Unknown Source)
    at me.snov.newrelic.elasticsearch.reporters.NodesStatsReporter.reportNodesStats(Unknown Source)
    at me.snov.newrelic.elasticsearch.ElasticsearchAgent.pollCycle(Unknown Source)
    at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:209)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by s12v** [comment]
@ojosdegris, which elasticsearch version do you use?

**Comment by viktor-evdokimov** [comment]
hi @s12v, somehow I did not get notification when you answered and only got one now, when you closed it. I solved that updating elasticsearch version to 2.x something. So surely keep this one closed. Thanks! ( and sorry for keeping it unanswered for a year)

**Comment by s12v** [comment]
@ojosdegris, good to know, thanks!
